export const moratoriumCruises = [
  'OSU-KM2201',
  'OSU-NBP1808',
  'OSU-NBP2002',
  'OSU-NBP1902',
  'OSU-SLM1801',
  'OSU-DLOR2201',
  'OSU-FROR2206',
  'OSU-FOOR2201',
  'OSU-OC1706B',
  'OSU-OC1804C',
  'OSU-OC1906A',
  'OSU-OC1908B',
  'OSU-OC2006A',
  'OSU-PMOR1806',
  'OSU-PMOR1808',
  'OSU-PMOR1907',
  'OSU-RR1807',
  'OSU-RR2208',
  'OSU-SP1716',
  'OSU-SR1801',
  'OSU-SR2113',
  'OSU-TT1811',
  'OSU-TT1909',
  'OSU-NRS2207',
  'OSU-SKQ2211',
  'OSU-OC2109A',
  'OSU-SKQ2303',
  'OSU-SKQ2306',
  'OSU-NBP2301',
  'OSU-NBP2302',
  'OSU-NBP2202',
  'OSU-CGOR2308',
  'OSU-CGOR2309',
  'OSU-DOOR2308',
  'OSU-DOOR2309',
  'OSU-LPOR2308',
  'OSU-LPOR2309',
  'OSU-AR2307',
  'OSU-SKQ202309T',
  'OSU-TN314',
  'OSU-PE2111',
  'OSU-SAFFONZ Torres',
  'OSU-CE24009',
  'OSU-NBP2403',
  'OSU-TN426',
  'OSU-TN435'
];

export const r2rCruiseLinks: { [key: string]: string[] } = {
  'OSU-AT0003': ['https://www.rvdata.us/search/cruise/AT3-49'],
  'OSU-BENTHIC3': ['https://www.rvdata.us/search/cruise/BNTH03MV'],
  'OSU-EW0104': ['https://www.rvdata.us/search/cruise/EW0104'],
  'OSU-EW0408': ['https://www.rvdata.us/search/cruise/EW0408'],
  'OSU-EW9504': ['https://www.rvdata.us/search/cruise/EW9504'],
  'OSU-EW9505': ['https://www.rvdata.us/search/cruise/EW9505'],
  'OSU-EW9709': ['https://www.rvdata.us/search/cruise/EW9709'],
  'OSU-FD7503': ['https://www.rvdata.us/search/cruise/FDRK03MV'],
  'OSU-HE0002': ['https://www.rvdata.us/search/cruise/HLY0001'],
  'OSU-INMD01': ['https://www.rvdata.us/search/cruise/INMD01MV'],
  'OSU-KM0419': ['https://www.rvdata.us/search/cruise/KM0419'],
  'OSU-M8011': ['https://www.rvdata.us/search/cruise/VLCN03MV','https://www.rvdata.us/search/cruise/VLCN04MV'],
  'OSU-M9907': ['https://www.rvdata.us/search/cruise/AVON09MV'],
  'OSU-ME0005A': ['https://www.rvdata.us/search/cruise/NEMO03MV'],
  'OSU-MV0209': ['https://www.rvdata.us/search/cruise/VANC02MV'],
  'OSU-MV0502': ['https://www.rvdata.us/search/cruise/TUIM03MV'],
  'OSU-MV0508': ['https://www.rvdata.us/search/cruise/TUIM13MV'],
  'OSU-MV0811': ['https://www.rvdata.us/search/cruise/BOLT02MV'],
  'OSU-MV1014': ['https://www.rvdata.us/search/cruise/MV1014'],
  'OSU-PE2111': ['https://www.rvdata.us/search/cruise/PE21-11'],
  'OSU-PLDS2': ['https://www.rvdata.us/search/cruise/PLDS02MV'],
  'OSU-PLUME02': ['https://www.rvdata.us/search/cruise/PLUM02WT'],
  'OSU-PLUTO3': ['https://www.rvdata.us/search/cruise/PLTO03MV'],
  'OSU-RAMA1': ['https://www.rvdata.us/search/cruise/RAMA01WT'],
  'OSU-RR0207': ['https://www.rvdata.us/search/cruise/LPRS02RR'],
  'OSU-RR0503': ['https://www.rvdata.us/search/cruise/ZHNG03RR'],
  'OSU-RR0603': ['https://www.rvdata.us/search/cruise/AMAT03RR'],
  'OSU-RR1310': ['https://www.rvdata.us/search/cruise/RR1310'],
  'OSU-RR1807': ['https://www.rvdata.us/search/cruise/RR1807'],
  'OSU-RR2208': ['https://www.rvdata.us/search/vessel/Revelle'],
  'OSU-RR9702A': ['https://www.rvdata.us/search/cruise/GENE03RR'],
  'OSU-SH1710': ['https://www.rvdata.us/search/cruise/HRS1710JH'],
  'OSU-SKQ1603': ['https://www.rvdata.us/search/cruise/SKQ201602S'],
  'OSU-SKQ1903': ['https://www.rvdata.us/search/cruise/SKQ201905S'],
  'OSU-SP1716': ['https://www.rvdata.us/search/cruise/SP1716'],
  'OSU-SR1801': ['https://www.rvdata.us/search/cruise/SR1801'],
  'OSU-SR2113': ['https://www.rvdata.us/search/cruise/SR2113'],
  'OSU-TN037': ['https://www.rvdata.us/search/cruise/TN037'],
  'OSU-TN0909': ['https://www.rvdata.us/search/cruise/TN240'],
  'OSU-TN314': ['https://www.rvdata.us/search/cruise/TN314'],
  'OSU-TT1811': ['https://www.rvdata.us/search/cruise/TN362'],
  'OSU-TT1909': ['https://www.rvdata.us/search/cruise/TN372'],
  'OSU-OC2109A': ['https://www.rvdata.us/search/cruise/OC2109A'],
  'OSU-OC1706B': ['https://www.rvdata.us/search/cruise/OC1706B'],
  'OSU-OC1804C': ['https://www.rvdata.us/search/cruise/OC1804C'],
  'OSU-OC1906A': ['https://www.rvdata.us/search/cruise/OC1906A'],
  'OSU-OC1908B': ['https://www.rvdata.us/search/cruise/OC1908B'],
  'OSU-OC2006A': ['https://www.rvdata.us/search/cruise/OC2006A'],
  'OSU-SKQ202309T': ['https://www.rvdata.us/search/cruise/SKQ202309T'],
  'OSU-SKQ202311S': ['https://www.rvdata.us/search/cruise/SKQ202311S'],
  'OSU-SKQ202404S': ['https://www.rvdata.us/search/cruise/SKQ202404S'],
  'OSU-SKQ202410S': ['https://www.rvdata.us/search/cruise/SKQ202410S'],
  'OSU-SKQ2012': ['https://www.rvdata.us/search/cruise/SKQ202016S'],
  'OSU-SKQ2211': ['https://www.rvdata.us/search/cruise/SKQ202215S'],
  'OSU-SKQ2303': ['https://www.rvdata.us/search/cruise/SKQ202305S'],
  'OSU-SKQ202206S': ['https://www.rvdata.us/search/cruise/SKQ202206S'],
  'OSU-SP2323': ['https://www.rvdata.us/search/cruise/SP2323'],
  'OSU-SR2510': ['https://www.rvdata.us/search/cruise/SR2510'],
  'OSU-W0903B': ['https://www.rvdata.us/search/cruise/W0903B'],
  'OSU-W0906A': ['https://www.rvdata.us/search/cruise/W0906A'],
  'OSU-W0906C': ['https://www.rvdata.us/search/cruise/W0906C'],
  'OSU-W0910B': ['https://www.rvdata.us/search/cruise/W0910B']
};

export const fileTypes = [
  'core-description',
  'core-image',
  'coring-data-sheet',
  'cruise-report',
  'ct-color-image',
  'ct-density',
  'ct-gray-image',
  'ct-image',
  'dredge-log',
  'field-image',
  //'itrax-image',
  //'itrax-xray-image',
  'mst-data',
  'ptmag-data',
  'publications-data',
  'samples-data',
  'thin-section-cross-polarized-foi-image',
  'thin-section-cross-polarized-image',
  'thin-section-plane-polarized-foi-image',
  'thin-section-plane-polarized-image',
  'whole-rock-foi-image',
  'whole-rock-image',
  'xray-image',
  'xrf-data'
];

export const fileTypeLabelMap: { [key: string]: string } = {
  'core-description': 'Core Description',
  'core-image': 'Core Image',
  'coring-data-sheet': 'Coring Data Sheet',
  'cruise-report': 'Cruise Report',
  'ct-color-image': 'CT Color Image',
  'ct-density': 'CT Density',
  'ct-gray-image': 'CT Gray Image',
  'ct-image': 'CT Image',
  'dredge-log': 'Dredge Log',
  'field-image': 'Field Image',
  //'itrax-image': 'ITRAX Image',
  //'itrax-xray-image': 'ITRAX X-Ray Image',
  'mst-data': 'MST Data',
  'ptmag-data': 'Point MS Data',
  'publications-data': 'Publications Data',
  'samples-data': 'Samples Data',
  'thin-section-cross-polarized-foi-image': 'Thin Section Cross-Polarized FOI',
  'thin-section-cross-polarized-image': 'Thin Section Cross-Polarized',
  'thin-section-plane-polarized-foi-image': 'Thin Section Plane-Polarized FOI',
  'thin-section-plane-polarized-image': 'Thin Section Plane-Polarized',
  'whole-rock-foi-image': 'Whole Rock FOI Image',
  'whole-rock-image': 'Whole Rock Image',
  'xray-image': 'X-Ray Image',
  'xrf-data': 'XRF Data'
};

export const hasFileTypeLabel = (fileType: string): boolean => {
  return fileType in fileTypeLabelMap;
};

export const getFileTypeLabel = (fileType: string): string => {
  return fileTypeLabelMap[fileType] || fileType;
};
